

import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {

  @override
  Map<String , Map<String, String>> get keys => {
    'en_US' : {
      'email_hint' : 'Email' ,
      'internet_exception' : "We're unable tp show results.\nPlease check your data\nconenction." ,
      'general_exception' : "We're unable to process your request.\n Please try again" ,
      'welcome_back' : 'Welcome\nBack' ,
      'login' :'Login' ,
      'password_hint' :'Password' ,
      'Create Category' :'Create Category' ,
      'Category Name' :'Category Name' ,
      'Enter category name' :'Enter category name' ,
      'Description' :'Category' ,
      'Brief description of the material' :'Brief description of the material' ,
      'Enter description' :'Enter description' ,
      'Create Category' :'Create Category' ,
      'Create Category' :'Create Category' ,
      'Category Name' :'Category Name' ,
      'Enter category name' :'Enter category name' ,
      'ex. Fruit' :'ex. Fruit' ,
      'Enter category name' :'Enter category name' ,
      'Description' :'Description' ,
      'Brief Description Of The Material' :'Brief Description Of The Material' ,
      'Enter description' :'Enter description' ,
      'Create Category' :'Create Category' ,
      'Create Client' :'Create Client' ,
      'Create Client' :'Create Client' ,
      'Client Name' :'Client Name' ,
      'Enter client name' :'Enter client name' ,
      'Address' :'Address' ,
      'Street 1' :'Street 1' ,
      'Enter street 1' :'Enter street 1' ,
      'Street 2' :'Street 2' ,
      'Country' :'Country' ,
      'Enter country' :'Enter country' ,
      'State' :'State' ,
      'Enter state' :'Enter state' ,
      'City' :'City' ,
      'Enter city' :'Enter city' ,
      'Postal Code' :'Postal Code' ,
      'Enter postal code' :'Enter postal code' ,
      'Phone Number' :'Phone Number' ,
      'Email Address' :'Email Address' ,
      'Enter valid email address' :'Enter valid email address' ,
      'Add Primary Contact' :'Add Primary Contact' ,
      'Point Of Contact' :'Point Of Contact' ,
      'Contact Name' :'Contact Name' ,
      'Enter contact name' :'Enter contact name' ,
      'Contact Number' :'Contact Number' ,
      'Email Address' :'Email Address' ,
      'Enter valid email address' :'Enter valid email address' ,
      'Client Detail' :'Client Detail' ,
      'Point Of Contact' :'Point Of Contact' ,
      'Name Of Person' :'Name Of Person' ,
      'Phone number' :'Phone number' ,
      'Email address' :'Email address' ,
      'Account' :'Account' ,
      'Account Name' :'Account Name' ,
      'Location' :'Location' ,
      'Email address' :'Email address' ,
      'Phone number' :'Phone number' ,
      'Address' :'Address' ,
      'Cold Storage' :'Category' ,
      'Farmhouse' :'Farmhouse' ,
      'Manager' :'Manager' ,
      'Phone Number' :'Phone Number' ,
      'Email Address' :'Email Address' ,
      'Edit Client' :'Edit Client' ,
      'Decline' :'Decline' ,
      'Accept' :'Accept' ,
      'Client List' :'Category' ,
      'Search Here. . .' :'Search Here. . .' ,
      'No Client Found' :'No Client Found' ,
      'Create Client' :'Create Client' ,
      'Incoming Request' :'Incoming Request' ,
      'Request Rejected' :'Request Rejected' ,
      'Request Sent' :'Request Sent' ,
      'Request Rejected' :'Request Rejected' ,
       'Location' :'Location' ,
       'Request' :'Request' ,
       'Inventory' :'Inventory' ,
       'Details' :'Details' ,
       'Add New Client' :'Add New Client' ,
       'Client Name' :'Client Name' ,
       'Search client' :'Search client' ,
       'No Client Found with this name' :'No Client Found with this name' ,
       'Create Client' :'Create Client' ,
       'Location' :'Location' ,
       'Send Request' :'Send Request' ,
       'Connected' :'Connected' ,
       'Incoming Request' :'Incoming Request' ,
       'Request Sent' :'Request Sent' ,
       'Sort By' :'Sort By' ,
       'No Inventory Found' :'No Inventory Found' ,
       'Name' :'Name' ,
       'Category' :'Category' ,
       'Total Quantity' :'Total Quantity' ,
       'Transaction Detail' :'Transaction Detail' ,
       'Do you want to perform action?' :'Do you want to perform action?' ,
       'Transaction ID' :'Transaction ID' ,
       'Transaction Date' :'Transaction Date' ,
       'Type' :'Type' ,
       'Client' :'Client' ,
       'Update' :'Update' ,
       'Unit' :'Unit' ,
       'Received' :'Received' ,
       'Remaining' :'Remaining' ,
       'Bin' :'Bin' ,
       'Expiry Date' :'Expiry Date' ,
       'Type' :'Type' ,
       'Return' :'Return' ,
       'Adjust' :'Adjust' ,
       'Type Of Adjustment' :'Type Of Adjustment' ,
       'Remove' :'Remove' ,
       'Add' :'Add' ,
       'Available quantity' :'Available quantity' ,
       'Quantity' :'Quantity' ,
       'Quantity Adjusted' :'Quantity Adjusted' ,
       'Enter quantity' :'Enter quantity' ,
       'Not have enough quantity available' :'Not have enough quantity available' ,
       'Date of Adjustment' :'Date of Adjustment' ,
       'Select date of adjustment' :'Select date of adjustment' ,
       'Reason for Adjustment' :'Reason for Adjustment' ,
       'Enter reason for adjustment' :'Enter reason for adjustment' ,
       'Comments/Notes' :'Comments/Notes' ,
       'Information' :'Information' ,
       'Confirm' :'Confirm' ,
       'Available quantity' :'Available quantity' ,
       'Quantity' :'Quantity' ,
       'Return Quantity' :'Return Quantity' ,
       'Enter quantity' :'Enter quantity' ,
       'Not have enough quantity available' :'Not have enough quantity available' ,
       'Date of Return' :'Date of Return' ,
       'Select date of return' :'Select date of return' ,
       'Reason Of Return' :'Reason Of Return' ,
       'Information' :'Information' ,
       'Enter reason for return' :'Enter reason for return' ,
       'Comments/Notes' :'Comments/Notes' ,
       'Information' :'Information' ,
       'Confirm' :'Confirm' ,
       'Transaction Date' :'Transaction Date' ,
       'Received' :'Received' ,
       'Remaining' :'Remaining' ,
       'Unit Name' :'Unit Name' ,
       'Type' :'Type' ,
       'Quantity' :'Quantity' ,
       'Category' :'Category' ,
       'UOM' :'UOM' 
    },
    'ur_PK' : {
      'email_hint' : 'asدسسدفاسف'
    },

  };
}