///
/// Generated file. Do not edit.
///
// coverage:ignore-file
// ignore_for_file: type=lint, unused_import

part of 'strings.g.dart';

// Path: <root>
typedef TranslationsEn = Translations; // ignore: unused_element
class Translations implements BaseTranslations<AppLocale, Translations> {
	/// Returns the current translations of the given [context].
	///
	/// Usage:
	/// final t = Translations.of(context);
	static Translations of(BuildContext context) => InheritedLocaleData.of<AppLocale, Translations>(context).translations;

	/// You can call this constructor and build your own translation instance of this locale.
	/// Constructing via the enum [AppLocale.build] is preferred.
	Translations({Map<String, Node>? overrides, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver})
		: assert(overrides == null, 'Set "translation_overrides: true" in order to enable this feature.'),
		  $meta = TranslationMetadata(
		    locale: AppLocale.en,
		    overrides: overrides ?? {},
		    cardinalResolver: cardinalResolver,
		    ordinalResolver: ordinalResolver,
		  ) {
		$meta.setFlatMapFunction(_flatMapFunction);
	}

	/// Metadata for the translations of <en>.
	@override final TranslationMetadata<AppLocale, Translations> $meta;

	/// Access flat map
	dynamic operator[](String key) => $meta.getTranslation(key);

	late final Translations _root = this; // ignore: unused_field

	// Translations
	String get loading => 'loading...';
	String get search_here => 'Search Here...';
	String get add_user => 'Add User';
	String get phone_number => 'Phone Number';
	String get email => 'Email';
	String get email_placeholder => 'abc@gmail.com';
	String get first_name => 'First Name';
	String get first_name_error => 'Enter first name';
	String get last_name => 'Last Name';
	String get last_name_error => 'Enter last name';
	String get select_user_role => 'Select User Role';
	String get select_your_role => 'Select Your Role';
	String get valid_email_error => 'Enter valid email address';
	String get select_role_error => 'Select your role';
	String get thank_you => 'Thank You !';
	String get sign_up_success => 'You Sign Up successfully';
	String get get_premium_at => 'Get Premium At';
	String get year_base_price => '/Year Base price';
	String get user_year => 'user /year';
	String get essential_features => 'Get started with all the essential features';
	String get user => '1 User';
	String get unlimited_entities => 'Unlimited Entities';
	String get unlimited_clients => 'Unlimited Clients';
	String get unlimited_assets => 'Unlimited Assets';
	String get unlimited_materials => 'Unlimited Materials';
	String get additional_users => 'Additional Users';
	String get add_to_plan => 'Add them to your plan!';
	String get proceed_to_pay => 'Proceed To Pay';
	String get welcome_message => 'Hi, Welcome To AgTech! 👋';
	String get first_name_label => 'First Name';
	String get first_name_hint => 'First Name';
	String get last_name_label => 'Last Name';
	String get last_name_hint => 'Last Name';
	String get phone_number_label => 'Phone Number';
	String get email_hint => 'example@gmail.com';
	String get otp_label => 'OTP';
	String get otp_hint => 'Enter Your OTP';
	String get password_hint => 'Enter Your Password';
	String get reenter_password_label => 'Re-Enter Your Password';
	String get sign_up_button => 'Sign Up';
	String get already_joined => 'Already Joined us?';
	String get login => 'Login';
	String get validation_error => 'Validation Error';
	String get otp_validation => 'Enter a valid OTP';
	String get send_otp => 'Send OTP';
	String get password_validation => 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
	String get welcome_back_message => 'Hi, Welcome Back! 👋';
	String get email_label => 'Email';
	String get password_label => 'Password';
	String get remember_me => 'Remember Me';
	String get forgot_password => 'Forgot password';
	String get login_button => 'Login';
	String get new_to_cold_storage => 'New to cold storage?  ';
	String get new_to_ag_tech => 'New to AgTech?  ';
	String get sign_up => 'Sign up';
	String get email_validation_error => 'Enter valid email address';
	String get password_error => 'Enter password';
	String get phone_number_hint => 'Phone Number';
	String get phone_number_error => 'Enter phone number';
	String get valid_phone_number_error => 'Enter valid phone number';
	String get home => 'Home';
	String get entity => 'Entity';
	String get entity_description => 'Manage and track all your cold storage facilities, warehouses, farms, and growers';
	String get vendors_and_customers => 'Vendors and Customers';
	String get vendors_and_customers_description => 'Add, view, and manage your vendors and customers';
	String get material => 'Material';
	String get material_description => 'Create and organize your materials, categories, and units of measurement';
	String get asset => 'Asset';
	String get asset_description => 'Track your equipment, machinery, and other valuable assets';
	String get create_password => 'Create Password';
	String get enter_new_password => 'Enter New Password';
	String get re_enter_your_password => 'Re-Enter Your Password';
	String get please_enter_new_password => 'Please enter your new password.';
	String get password_requirements => 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
	String get passwords_do_not_match => 'Passwords do not match';
	String get logout => 'Logout';
	String get create_password_button => 'Create Password';
	String get account_name => 'Account Name';
	String get email_address => 'Email Address';
	String get street1 => 'Street 1';
	String get street2 => 'Street 2';
	String get country => 'Country';
	String get create_account => 'Create Account!';
	String get continue_text => 'Continue';
	String get address => 'Address';
	String get separator => '.......................';
	String get state => 'State';
	String get city => 'City';
	String get postal_code => 'Postal Code';
	String get different_billing_address => 'Different Billing Address ?';
	String get logo => 'Logo';
	String get default_language => 'Default Language';
	String get time_zone => 'Time Zone';
	String get description => 'Description';
	String get selectDefault_language => 'Select default language';
	String get select_timezone => 'Select Timezone';
	String get upload => 'Upload';
	String get empty_account_name => 'Enter account name';
	String get invalid_email => 'Enter valid email address';
	String get empty_street1 => 'Enter street 1';
	String get empty_country => 'Enter country';
	String get empty_state => 'Enter state';
	String get empty_city => 'Enter city';
	String get empty_postal_code => 'Enter postal code';
	String get error_select_default_language => '   Select default language';
	String get error_select_timezone => '   Select timezone';
	String get languages_en => 'English';
	String get languages_sp => 'Spanish';
	String get user_list => 'User List';
	String get noUser_left => 'No user left';
	String get seats_available => 'seats available';
	String get update_user => 'Update User';
	String get inactive => 'Inactive';
	String get active => 'Active';
	String get update_user_button => 'Update User';
	String get enter_first_name => 'Enter first name';
	String get enter_last_name => 'Enter last name';
	String get select_your_role_error => '   Select your role';
	String get transaction => 'Transaction';
	String get date => 'Date';
	String get type => 'Type';
	String get noTransaction_found => 'No Transaction Found';
	String get sort_by => 'Sort By';
	String get dispatcher => 'Dispatcher';
	String get receiver => 'Receiver';
	String get customer => 'Customer';
	String get vendor => 'Vendor';
	String get transfer_in => 'T-IN';
	String get transfer_out => 'T-OUT';
	String get out => 'OUT';
	String get in_text => 'IN';
	String get search_placeholder => 'Search...';
	String get transaction_id => 'Transaction ID';
	String get transaction_date => 'Transaction Date';
	String get received => 'Received';
	String get damage => 'Damage';
	String get remaining => 'Remaining';
	String get adjust => 'Adjust';
	String get return_text => 'Return';
	String get transfer => 'Transfer';
	String get in_transit => 'IN Transit';
	String get status => 'Status';
	String get transaction_type => 'Transaction Type';
	String get available_quantity => 'Available quantity';
	String get return_quantity => 'Return Quantity';
	String get date_of_return => 'Date of Return';
	String get reason_of_return => 'Reason Of Return';
	String get comments_notes => 'Comments/Notes';
	String get confirm => 'Confirm';
	String get cancel => 'Cancel';
	String get add_new_user => 'Add new user';
	String get error_no_user_left => 'Error';
	String get no_user_left_message => 'No user left';
	String get valid_email => 'Enter valid email address';
	String get user_role => 'User Role';
	String get select_role => '   Select your role';
	String get select_role_text => 'Select role';
	String get count => 'Count';
	String get get_started_features => 'Get started with all the essential features';
	String get add_them_to_your_plan => 'Add them to your plan!';
	String get this_reflected_next_billing => 'This will be reflected in your next billing cycle';
	String get proceed => 'Proceed';
	String get setting => 'Setting';
	String get user_management => 'User Management';
	String get entity_settings => 'Entity Settings';
	String get account_setting => 'Account Setting';
	String get subscription => 'Subscription';
	String get reports => 'Reports';
	String get update_profile => 'Update Profile';
	String get enter_your_email => 'Enter Your Email';
	String get example_email => 'example@gmail.com';
	String get enter_valid_email => 'Enter valid email address';
	String get update => 'Update';
	String get update_password => 'Update Password';
	String get re_enter_password => 'Re-Enter Your Password';
	String get profile => 'Profile';
	String get create_entity => 'Create Entity';
	String get reports_occurrences => 'Reports Occurrences';
	String get no_report_found => 'No Report Found';
	String get daily => 'Daily';
	String get weekly => 'Weekly';
	String get monthly => 'Monthly';
	String get entity_listing => 'Entity Listing';
	String get update_account => 'Update Account';
	String get back => 'Back';
	String get phone => 'Phone Number';
	String get street_1 => 'Street 1';
	String get street_2 => 'Street 2';
	String get billing_address => 'Different Billing Address ?';
	String get account_name_required => 'Enter account name';
	String get email_invalid => 'Enter valid email address';
	String get street_1_required => 'Enter street 1';
	String get country_required => 'Enter country';
	String get state_required => 'Enter state';
	String get city_required => 'Enter city';
	String get postal_code_required => 'Enter postal code';
	String get no_entity_found => 'No Entity Found';
	String get assigned => 'Assigned';
	String get remove => 'Remove';
	String get add => 'Add';
	String get cold_storage => 'Cold Storage';
	String get farmhouse => 'Farmhouse';
	String get save => 'Save';
	String get notifications => 'Notifications';
	String get no_notification_found => 'No Notification Found';
	String get has_transferred_new_material => 'Has transferred a new material';
	String get please_enter_phone_number => 'Please enter phone number';
	String get create_unit => 'Create Unit';
	String get material_name => 'Material Name';
	String get category => 'Category';
	String get measurement_of_unit => 'Measurement of Unit';
	String get unit_name => 'Unit Name';
	String get uom => 'UOM';
	String get action => 'Action';
	String get unit_of_measurements => 'Unit Of Measurements';
	String get select_unit_of_measurements => '   Select unit of measurements';
	String get add_new_material => 'Add New Material';
	String get no_material_found => 'No Material Found';
	String get add_material => 'Add Material';
	String get name => 'Name';
	String get edit => 'Edit';
	String get delete => 'Delete';
	String get create_material => 'Create Material';
	String get material_name_hint => 'ex. Apple';
	String get description_hint => 'Description';
	String get select_category => 'Select Category';
	String get select_uom => 'Select UOM';
	String get create_new_material => 'Create New Material';
	String get enter_material_name => 'Enter material name';
	String get enter_description => 'Enter description';
	String get enter_unit_name => 'Enter unit name';
	String get select_material_category => 'Select material category';
	String get select_material_uom => 'Select material UOM';
	String get add_material_quantity => 'Add Material Quantity';
	String get enter_name_of_unit => 'Enter Name Of Unit';
	String get unit_quantity => 'Unit quantity';
	String get enter_quantity => 'Enter quantity';
	String get quality_type => 'Quality type';
	String get quality_type_hint => 'Quality Type';
	String get storage_conditions => 'Storage Conditions';
	String get add_storage_conditions => 'Add Storage Conditions';
	String get safety_data => 'Safety Data';
	String get brief_safety_data => 'Brief Safety Data Or Handling Instructions.';
	String get compliance_certificates => 'Compliance Certificates';
	String get add_certificate => 'Add Certificate';
	String get regulatory_information => 'Regulatory Information';
	String get regulatory_information_hint => 'Regulatory Information Or Restrictions.';
	String get additional_information => 'Additional Information';
	String get create => 'Create';
	String get specification => 'Specification';
	String get add_imperial_unit => 'Add Imperial Unit';
	String get length => 'Length';
	String get length_hint => 'Length';
	String get width => 'Width';
	String get width_hint => 'Width';
	String get height => 'Height';
	String get height_hint => 'Height';
	String get diameter => 'Diameter';
	String get diameter_hint => 'Diameter';
	String get weight => 'Weight';
	String get weight_hint => 'Weight';
	String get color => 'Color';
	String get color_hint => 'Color';
	String get signature => 'Signature';
	String get no_content => 'No content';
	String get submit => 'Submit';
	String get image_path => 'assets/images/ic_close_dialog.png';
	String get background_color => 'Colors.grey';
	String get signature_background_color => 'Colors.white';
	String get dialog_warning_title => 'Warning';
	String get dialog_warning_message => 'This is an irreversible action. Do you want to proceed?';
	String get dialog_delete_title => 'Alert';
	String get dialog_delete_message => 'Are you sure you want to delete this?';
	String get dialog_ok_btn_text => 'Proceed';
	String get dialog_cancel_btn_text => 'Cancel';
	String get dialog_delete_ok_btn_text => 'Yes';
	String get dialog_delete_cancel_btn_text => 'No';
	String get dialog_ok_button_color => '#005AFF';
	String get dialog_cancel_button_color => '#D9D9D9';
	String get dialog_ok_button_text_color => '#FFFFFF';
	String get dialog_cancel_button_text_color => '#000000';
	String get dialog_title_color => '#FF0000';
	String get dialog_title_font_weight => '500';
	String get dialog_title_font_size => '20';
	String get dialog_content_color => '#000000';
	String get dialog_content_font_weight => '500';
	String get dialog_content_font_size => '20';
	String get dialog_img_limit_validation => 'Upload Limit Reached';
	String get dialog_upload_limit_warning => 'You have reached the maximum upload limit.';
	String get dialog_img_count_validation => 'You can upload a maximum of 5 images.';
	String get dialog_img_size_validation => 'Total upload size cannot exceed 10 MB.';
	String get dialog_ok_text => 'Ok';
	String get pageHeading => 'Specification';
	String get addImperialUnit => 'Add Imperial Unit';
	String get update_material_quantity => 'Update Material Quantity';
	String get select_a_quality_type => 'Select a quality type';
	String get brief_safety_data_or_handling_instructions => 'Brief Safety data or handling instructions.';
	String get regulatory_information_or_restrictions => 'Regulatory information or restrictions.';
	String get enter_tag => 'Enter tag...';
	String get add_category => 'Add Category';
	String get update_material => 'Update Material';
	String get select_bin => 'Select Bin';
	String get need_custom_mapping => 'Need Custom Mapping';
	String get select_material => 'Select Material';
	String get your_account => 'Your Account';
	String get details => 'Details';
	String get incoming_material => 'Incoming Material';
	String get reject => 'Reject';
	String get accept => 'Accept';
	String get quantity => 'Quantity';
	String get receipt_date => 'Receipt Date';
	String get driver_name => 'Driver Name';
	String get material_in_successfully => 'Material IN Successfully';
	String get dashboard => 'V&C Dashboard';
	String get material_transfer => 'Material Transfer';
	String get date_of_transfer => 'Date of Transfer';
	String get expiration_date => 'Expiration Date';
	String get quantity_transfer => 'Quantity Transfer';
	String get reason_for_transfer => 'Reason for Transfer';
	String get generate => 'Generate';
	String get add_transfer_date => 'Add transfer date';
	String get enter_quantity_more_than_0 => 'Enter quantity more than 0';
	String get no_quantity_available => 'No quantity available for out';
	String get not_enough_quantity => 'Not enough quantity available to dispatch';
	String get material_transfer_success => 'Material Transfer Successfully';
	String get transfer_request => 'Transfer Request';
	String get entity_from => 'Entity From';
	String get entity_to => 'Entity To';
	String get material_in_transit => 'Material is in Transit';
	String get add_quantity => 'Add Quantity';
	String get quantity_dispatched => 'Quantity Dispatched';
	String get notes => 'Notes';
	String get upload_images => 'Upload Images';
	String get view_all => 'View All';
	String get add_images => 'Add Images';
	String get supports => 'Supports: PNG, JPG, JPEG, WEBP';
	String get select_category_error => '   Select a category';
	String get select_material_error => '   Select a material';
	String get enter_quantity_more_than_zero => 'Enter quantity more than 0';
	String get add_more_quantity => 'Add More Quantity';
	String get transportation_details => 'Transportation Details';
	String get add_signature => 'Add Signature';
	String get click_here_to_draw_signature => 'Click here to draw signature';
	String get bin => 'Bin';
	String get material_out => 'Material OUT';
	String get date_of_dispatch => 'Date of Dispatch';
	String get select => 'Select';
	String get please_add_quantity => 'Please add quantity';
	String get please_add_signature => 'Please add signature';
	String get error => 'Error';
	String get select_customer_name => 'Select a customer name';
	String get select_entity => 'Select an entity';
	String get enter_entity_name => 'Enter entity name';
	String get select_date_of_dispatch => 'Select date of dispatch';
	String get date_of_dispatch_hint => 'Date of Dispatch';
	String get warning => 'Warning';
	String get irreversible_action => 'This is an irreversible action. Do you want to proceed?';
	String get alert => 'Alert';
	String get yes => 'Yes';
	String get no => 'No';
	String get delete_confirmation => 'Are you sure you want to delete this item?';
	String get add_photo => 'Add Photo';
	String get camera => 'Camera';
	String get library => 'Library';
	String get take_photo_from => 'From where do you want to take the photo?';
	String get update_quantity => 'Update Quantity';
	String get select_unit => 'Select Unit';
	String get select_a_category => 'Select a category';
	String get select_a_material => 'Select a material';
	String get select_a_unit => 'Select a unit';
	String get enter_more_than_zero => 'Enter quantity more than 0';
	String get select_bin_prompt => 'Select Bin';
	String get notes_hint => 'Notes';
	String get quantity_hint => 'Quantity';
	String get text_material_in_update => 'Material IN Update';
	String get text_entity => 'Entity';
	String get text_vendor => 'Vendor';
	String get text_date_of_receipt => 'Date of Receipt';
	String get text_add_quantity => 'Add Quantity';
	String get text_add_more_quantity => 'Add more Quantity';
	String get text_select => 'Select';
	String get text_select_a_vendor => 'Select a vendor';
	String get text_select_date_of_receipt => 'Select date of receipt';
	String get text_update_material => 'Update Material';
	String get text_back => 'Back';
	String get text_generate => 'Generate';
	String get text_error => 'Error';
	String get text_please_add_signature => 'Please add signature';
	String get text_driver_name => 'Driver Name';
	String get text_signature => 'Signature';
	String get text_add_signature => 'Add Signature';
	String get text_click_here_draw_signature => 'Click here to draw signature';
	String get text_bin => 'Bin';
	String get text_quantity => 'Quantity';
	String get text_uom => 'UOM';
	String get text_transportation_details => 'Transportation Details';
	String get text_thank_you => 'Thank You !';
	String get text_material_updated => 'Material Updated Successfully';
	String get text_material_in_success => 'Material IN Successfully';
	String get text_dashboard => 'Dashboard';
	String get text_category => 'Category';
	String get text_select_category => 'Select Category';
	String get text_material => 'Material';
	String get text_select_material => 'Select Material';
	String get text_unit => 'Unit';
	String get text_select_unit => 'Select Unit';
	String get text_expiration_date => 'Expiration Date';
	String get text_quantity_received => 'Quantity Received';
	String get text_damage_quantity_received => 'Damage Quantity Received';
	String get text_any_damage => 'Any Damage';
	String get text_upload_images => 'Upload Images';
	String get text_view_all => 'View All';
	String get text_add_images => 'Add Images';
	String get text_supports_formats => 'Supports: PNG, JPG, JPEG, WEBP';
	String get text_material_in => 'Material IN';
	String get text_error_enter_entity_name => 'Enter entity name';
	String get text_error_select_vendor => '   Select a vendor';
	String get text_error_select_date => 'Select date of receipt';
	String get text_error_add_quantity => 'Please add quantity';
	String get text_error_add_signature => 'Please add signature';
	String get text_error_enter_driver_name => 'Enter driver name';
	String get text_click_to_draw_signature => 'Click here to draw signature';
	String get text_na => 'NA';
	String get text_select_bin => 'Select Bin';
	String get text_error_select_category => '   Select a category';
	String get text_error_select_material => '   Select a material';
	String get text_error_select_unit => '   Select a unit';
	String get text_error_enter_quantity => 'Enter quantity';
	String get text_error_enter_damage_quantity => 'Enter damage quantity';
	String get text_error_damage_quantity_must_be_less => 'Damage quantity must be less than received quantity';
	String get hint_select_category => 'Select Category';
	String get hint_select_material => 'Select Material';
	String get hint_select_unit => 'Select Unit';
	String get hint_expiration_date => 'Expiration Date';
	String get hint_quantity => 'Quantity';
	String get hint_damage_quantity => 'Quantity';
	String get text_any_breakage => 'Any Breakage';
	String get text_supported_formats => 'Supports: PNG, JPG, JPEG, WEBP';
	String get error_empty_quantity => 'Please add quantity first';
	String get text_inventory => 'Inventory';
	String get text_unit_name => 'Unit Name';
	String get text_type => 'Type';
	String get error_message => 'Please add quantity first';
	String get text_transaction => 'Transaction';
	String get text_no_transaction_found => 'No Transaction Found';
	String get icon_back_button => 'assets/images/ic_back_btn.png';
	String get icon_home => 'assets/images/default/ic_home.svg';
	String get icon_notification => 'assets/images/ic_notification_bell.png';
	String get image_empty_list => 'assets/images/ic_blank_list.png';
	String get header_transaction_date => 'Transaction Date';
	String get header_received => 'Received';
	String get header_remaining => 'Remaining';
	String get return_quantity_hint => 'Return Quantity';
	String get date_of_return_hint => 'Date of Return';
	String get information_hint => 'Information';
	String get comments_notes_hint => 'Information';
	String get enter_quantity_error => 'Enter quantity';
	String get not_enough_quantity_error => 'Not have enough quantity available';
	String get select_date_error => 'Select date of return';
	String get enter_reason_error => 'Enter reason for return';
	String get text_field_placeholder => '.................................................................................................................................................................................................................................................';
	String get return_button_text => 'Return';
	String get adjust_button_text => 'Adjust';
	String get type_of_adjustment_text => 'Type Of Adjustment';
	String get remove_text => 'Remove';
	String get add_text => 'Add';
	String get available_quantity_text => 'Available Quantity';
	String get quantity_adjusted_text => 'Quantity Adjusted';
	String get date_of_adjustment_text => 'Date of Adjustment';
	String get select_date_of_adjustment_text => 'Select date of adjustment';
	String get reason_for_adjustment_text => 'Reason for Adjustment';
	String get enter_reason_of_adjustment_text => 'Enter reason for adjustment';
	String get comments_notes_text => 'Comments/Notes';
	String get transaction_id_text => 'Transaction ID';
	String get transaction_date_text => 'Transaction Date';
	String get type_text => 'Type';
	String get vendor_text => 'Vendor';
	String get received_text => 'Received';
	String get remaining_text => 'Remaining';
	String get bin_text => 'Bin';
	String get expiry_date_text => 'Expiry Date';
	String get transaction_detail_text => 'Transaction Detail';
	String get perform_action_text => 'Do you want to perform action?';
	String get inventory_text => 'Inventory';
	String get material_text => 'Material';
	String get category_text => 'Category';
	String get quantity_text => 'Quantity';
	String get no_inventory_found_text => 'No Inventory Found';
	String get sort_by_hint_text => 'Sort By';
	String get client_text => 'Client';
	String get materials_text => 'Materials';
	String get total_quantity_text => 'Total Quantity';
	String get gallery_text => 'Gallery';
	String get no_image_found_text => 'No Image Found';
	String get reset_password_text => 'Reset Password';
	String get change_password_text => 'Change Password';
	String get verification_code_prompt => 'Please enter your verification code.';
	String get verification_code_info => 'We have sent a verification code to your registered email ID.';
	String get enter_otp_label => 'Enter Your OTP';
	String get enter_otp_hint => 'Enter Your OTP';
	String get enter_new_password_label => 'Enter New Password';
	String get enter_new_password_hint => 'Enter New Password';
	String get reenter_password_hint => 'Enter Your Password';
	String get password_validation_error => 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
	String get otp_validation_error => 'Enter valid otp';
	String get forgot_password_title => 'Forgot Password';
	String get submit_button_text => 'Submit';
	String get registered_email_prompt => 'Please enter your registered email ID.';
	String get registered_email_prompt_desc_text => 'We will send a verification code to your registered email ID.';
	String get update_farm_grower_title => 'Update Farm/Grower';
	String get farm_name_label => 'Farm Name';
	String get farm_name_validation_error => 'Enter farm name';
	String get address_label => 'Address';
	String get address_hint => 'Address';
	String get address_validation_error => 'Enter address';
	String get phone_label => 'Phone';
	String get profile_picture_label => 'Profile Picture';
	String get upload_button_text => 'Upload';
	String get farm_size_label => 'Farm Size (Acres)';
	String get farm_size_validation_error => 'Enter farm size';
	String get type_of_farming_label => 'Type Of Farming';
	String get additional_details_label => 'Additional Details';
	String get owner_name => 'Owner Name';
	String get created_by => 'Created By';
	String get manager_name => 'Manager Name';
	String get farming_method => 'Farming Method';
	String get irrigation_system => 'Irrigation System';
	String get type_of_soil => 'Type Of Soil';
	String get storage_facilities => 'Storage Facilities';
	String get add_button => 'Update Entity';
	String get farming_method_hint => 'Farming Method';
	String get irrigation_system_hint => 'Details of Irrigation System Used';
	String get type_of_soil_hint => 'Add Soil Type';
	String get compliance_certificates_hint1 => 'Add Certificate';
	String get compliance_certificates_hint2 => 'Enter tag...';
	String get storage_facilities_hint1 => 'Add Storage Facility';
	String get storage_facilities_hint2 => 'Enter tag...';
	String get add_farm_grower => 'Add Farm/Grower';
	String get add_entity => 'Add Entity';
	String get entity_list => 'Entity List';
	String get location => 'Location';
	String get request => 'Request';
	String get setup_finish => 'Setup Finish';
	String get cold_storage_warehouse => 'Cold Storage | Warehouse';
	String get farm_grower => 'Farm | Grower';
	String get create_cold_storage_subheading => 'Create and manage your cold storage and/or warehouses for efficient storage and distribution.';
	String get create_farmhouse_subheading => 'Add and oversee your farms and/or growers to track production and inventory.';
	String get entity_details => 'Entity Details';
	String get material_in => 'Material In';
	String get view_inventory => 'View Inventory';
	String get view_transactions => 'Transaction Log';
	String get update_cold_storage => 'Update Cold Storage/Warehouse';
	String get additional_details => 'Additional Details';
	String get storage_name => 'Storage Name';
	String get profile_picture => 'Profile Picture';
	String get add_bin => 'Add Bin';
	String get add_more_bin => 'Add more Bin';
	String get storage_capacity => 'Storage Capacity';
	String get temperature_range => 'Temperature Range (°F)';
	String get regulation_information => 'Regulation Information';
	String get safety_measures => 'Safety Measures';
	String get add_safety_measures => 'Add Safety Measures';
	String get operational_hours => 'Operational Hours';
	String get update_entity => 'Update Entity';
	String get add_cold_storage => 'Add Cold Storage/Warehouse';
	String get storage_condition => 'Storage Condition';
	String get select_storage => 'Select a storage';
	String get select_manager_hint => 'Select Manager';
	String get select_manager_error_text => '   Select a manager';
	String get enter_storage_condition => 'Enter storage condition';
	String get max_limit_250_words => 'Max limit 250 words';
	String get enter_storage_capacity => 'Enter storage capacity';
	String get bin_creation => 'Bin Creation';
	String get bin_name => 'Bin Name';
	String get enter_bin_name => 'Enter bin name';
	String get type_of_storage => 'Type Of Storage';
	String get select_type_of_storage => 'Select Type Of Storage';
	String get select_a_storage => '   Select a storage';
	String get max_temp => 'Max Temp';
	String get max_button_text => 'Max';
	String get enter_max_temp => 'Enter max temp';
	String get must_be_a_number => 'Must be a number';
	String get must_be_greater_than_max => 'Must be greater than Max';
	String get min_temp => 'Min Temp';
	String get min_button_text => 'Min';
	String get enter_min_temp => 'Enter min temp';
	String get must_be_less_than_max => 'Must be less than Max';
	String get humidity_range => 'Humidity Range (%)';
	String get max_humidity => 'Max Humidity';
	String get enter_max_humidity => 'Enter max humidity';
	String get min_humidity => 'Min Humidity';
	String get enter_min_humidity => 'Enter min humidity';
	String get update_bin => 'Update Bin';
	String get greater_than_max => 'Must be greater than Max';
	String get less_than_max => 'Must be less than Max';
	String get bin_name_hint => 'Bin name';
	String get storage_condition_hint => 'Information';
	String get storage_capacity_hint => 'Storage Capacity';
	String get enter_storage_name => 'Enter storage name';
	String get asset_creation => 'Asset Creation';
	String get basic_asset_information => 'Basic Asset Information';
	String get purchase_and_financial_details => 'Purchase and Financial Details';
	String get operational_details => 'Operational Details';
	String get insurance_and_compliance => 'Insurance and Compliance';
	String get purchase_date => 'Purchase Date';
	String get insurance_expiry_date => 'Insurance Expiry Date';
	String get insurance_provider => 'Insurance Provider';
	String get insurance_policy_number => 'Insurance Policy Number';
	String get purchase_price => 'Purchase Price';
	String get vendor_name => 'Vendor Name';
	String get vendor_contact_number => 'Vendor Contact Number';
	String get vendor_email => 'Vendor Email';
	String get invoice_number => 'Invoice Number';
	String get warranty_details => 'Warranty Details';
	String get asset_name => 'Asset Name';
	String get manufacturer => 'Manufacturer';
	String get model => 'Model';
	String get serial_number => 'Serial Number';
	String get operational_status => 'Operational Status';
	String get condition => 'Condition';
	String get last_updated => 'Last Updated';
	String get create_new_asset => 'Create New Asset';
	String get no_asset_found => 'No Asset Found';
	String get create_asset => 'Create Asset';
	String get current_location => 'Current Location';
	String get assigned_to => 'Assigned To';
	String get available => 'Available';
	String get occupied => 'Occupied';
	String get assign => 'Assign';
	String get assign_new => 'Assign New';
	String get release => 'Release';
	String get history => 'History';
	String get no_history_found => 'No History Found';
	String get date_from => 'Date from';
	String get date_to => 'Date To';
	String get yyyy_mm_dd => 'YYYY-MM-DD';
	String get blank_list_image => 'assets/images/ic_blank_list.png';
	String get calendar_image => 'assets/images/ic_calender.png';
	String get create_asset_category => 'Create Asset Category';
	String get category_name => 'Category Name';
	String get enter_category_name => 'Enter category name';
	String get brief_description => 'Brief Description';
	String get create_category => 'Create Category';
	String get close_dialog_image => 'assets/images/ic_close_dialog.png';
	String get new_assign => 'New Assign';
	String get select_location => 'Select location';
	String get asset_cant_be_assigned => 'Asset can\'t be assigned to it\'s current location';
	String get select_user => 'Select user';
	String get end_date => 'End Date';
	String get enter_end_date => 'Enter end date';
	String get usage => 'Usage';
	String get enter_usage => 'Enter usage';
	String get note => 'Note';
	String get brief_usage => 'Brief Usage';
	String get note_hint => 'Note';
	String get end_date_hint => 'End Date';
	String get model_number_hint => 'Model number';
	String get asset_updation => 'Asset Updation';
	String get divider_color => '#E7E7E7';
	String get arrow_up_icon => 'assets/images/ic_arrow_up.png';
	String get arrow_down_icon => 'assets/images/ic_arrow_down.png';
	String get calendar_icon => 'assets/images/ic_calender.png';
	String get back_button_icon => 'assets/images/ic_back_btn.png';
	String get update_asset => 'Update Asset';
	String get select_asset_category_error_text => '   Select asset category';
	String get enter_asset_name__error_text => 'Enter asset name';
	String get enter_manufacturer_error_text => 'Enter manufacturer';
	String get enter_model_number_error_text => 'Enter model number';
	String get enter_serial_number_error_text => 'Enter serial number';
	String get inventory => 'Inventory';
	String get no_transaction_found => 'No Transaction Found';
	String get transaction_detail => 'Transaction Detail';
	String get do_you_want_to_perform_action => 'Do you want to perform action?';
	String get unit => 'Unit';
	String get quantity_type_name => 'NA';
	String get type_of_adjustment => 'Type Of Adjustment';
	String get quantity_adjusted => 'Quantity Adjusted';
	String get date_of_adjustment => 'Date of Adjustment';
	String get reason_for_adjustment => 'Reason for Adjustment';
	String get hint_date_of_return => 'Date of Return';
	String get hint_information => 'Information';
	String get hint_comments_notes => 'Information';
	String get select_date_of_return => 'Select date of return';
	String get enter_reason_for_return => 'Enter reason for return';
	String get no_inventory_found => 'No Inventory Found';
	String get total_quantity => 'Total Quantity';
	String get enter_name => 'Enter name';
	String get enter_street_1 => 'Enter street 1';
	String get enter_country => 'Enter country';
	String get enter_state => 'Enter state';
	String get enter_city => 'Enter city';
	String get enter_postal_code => 'Enter postal code';
	String get add_primary_contact => 'Add Primary Contact';
	String get point_of_contact => 'Point Of Contact';
	String get contact_name => 'Contact Name';
	String get enter_contact_name => 'Enter contact name';
	String get contact_number => 'Contact Number';
	String get add_vendor_customer => 'Add Vendor & Customer';
	String get search_by_account_name => 'Search by Account Name';
	String get no_account_found => 'No Account found with this name';
	String get send_request => 'Send Request';
	String get you_want_to_add_them_as => 'You want to add them as';
	String get connected => 'Connected';
	String get incoming_request => 'Incoming Request';
	String get request_sent => 'Request Sent';
	String get v_c_list => 'V&C List';
	String get no_record_found => 'No Record Found';
	String get create_new_vendor => 'Create New Vendor';
	String get request_rejected => 'Request Rejected';
	String get v_and_c_detail => 'V&C Detail';
	String get name_of_person => 'Name Of Person';
	String get account => 'Account';
	String get account_name_hint => 'Account Name';
	String get location_hint => 'Location';
	String get phone_hint => 'Phone number';
	String get manager => 'Manager';
	String get edit_client => 'Edit Client';
	String get decline => 'Decline';
	String get enter_street_2 => 'Enter street 2';
	String get enter_valid_email_address => 'Enter valid email address';
	String get brief_description_of_material => 'Brief description of the material';
	String get create_category_button => 'Create Category';
	String get brief_description_of_the_material => 'Brief Description Of The Material';
	String get warning_title => 'Warning';
	String get proceed_button_text => 'Proceed';
	String get cancel_button_text => 'Cancel';
	String get admin_role => 'Admin';
	String get manager_role => 'Manager';
	String get employee_role => 'Employee';
	String get assign_text => 'Assign';
	String get status_text => 'Status';
	String get active_status => 'Active';
	String get inactive_status => 'Inactive';
	String get email_address_label => 'Email Address';
	String get status_label => 'Status';
	String get details_label => 'Details';
	String get assign_by_label => 'Assign By';
	String get usage_label => 'Usage';
	String get note_label => 'Note';
	String get from_label => 'From';
	String get to_label => 'To';
	String get close_button_label => 'Close';
	String get success_text => 'Success';
	String get error_text => 'Error';
	String get validation_error_text => 'Validation Error';
	String get account_created_success_text => 'Account created successfully';
	String get session_expired_text => 'Session is expired or invalid need to login again';
	String get subscribed_success_text => 'Subscribed successfully';
	String get category_added_success_text => 'Category added successfully';
	String get record_delete_success_text => 'Record has been successfully deleted';
	String get entity_created_success_text => 'Entity created successfully';
	String get material_created_success_text => 'Material created successfully';
	String get added_text => 'Added';
	String get material_unit_added_success_text => 'Material unit added successfully';
	String get signup_success_text => 'Signed up successfully';
	String get login_success_text => 'Logged in successfully';
	String get user_created_success_text => 'User created successfully';
	String get otp_sent_text => 'OTP SENT';
	String get otp_sent_message_text => 'Sent an OTP at your email, please check. OTP will be valid till next 2 minutes';
	String get first_name_last_name_email_required => 'First name, Last name, Email is required';
	String get transaction_adjusted_success_text => 'Transaction adjusted successfully';
	String get transaction_return_success_text => 'Transaction return successfully';
	String get account_updated_success_text => 'Account updated successfully';
	String get record_updated_success_text => 'Record updated successfully';
	String get request_accepted_success_text => 'Request accept successfully';
	String get request_declined_success_text => 'Request declined successfully';
	String get request_sent_success_text => 'Request sent successfully';
	String get record_created_success_text => 'Record created successfully';
	String get asset_updated_success_text => 'Asset updated successfully';
	String get asset_assigned_success_text => 'Asset assigned successfully';
	String get asset_success_release_text => 'Asset successfully release';
	String get asset_created_success_text => 'Asset created successfully';
	String get password_updated_success_text => 'Password updated successfully';
	String get entity_updated_success_text => 'Entity updated successfully';
	String get material_unit_updated_success_text => 'Material unit updated successfully';
	String get material_transfer_rejected_text => 'Material transfer rejected';
	String get quantity_added_success_text => 'Quantity Added Successfully';
	String get transaction_updated_success_text => 'Transaction Updated Successfully';
	String get quantity_updated_success_text => 'Quantity updated successfully';
	String get transfer_request_sent_success_text => 'Transfer request sent Successfully';
	String get material_request_accepted_success_text => 'Material request accepted successfully';
	String get material_request_rejected_success_text => 'Material request rejected successfully';
	String get selected_material_mapped_success_text => 'Selected material mapped successfully';
	String get user_updated_success_text => 'User updated successfully';
	String get user_removed_from_entity => 'User removed from the entity';
	String get user_assigned_to_entity => 'User successfully assigned to the entity';
	String get bin_name_already_exists_text => 'The bin name is already exists';
	String get bin_created_success_text => 'Bin created successfully';
	String get bin_updated_success_text => 'Bin updated successfully';
	String get email_sent_success_text => 'Email sent successfully';
	String get password_reset_success_text => 'Password reset successfully';
	String get report_request_save_success_text => 'Report request save successfully';
	String get profile_updated_success_text => 'Profile updated successfully';
	String get subscribe_updated_success_text => 'Subscribe updated successfully';
	String get account_delete_permission_text => 'Do you want to delete this account ?';
	String get account_delete_warning_text => 'This will delete your account permanently.';
	String get account_deleted_success_text => 'Account deleted successfully.';
}

/// Flat map(s) containing all translations.
/// Only for edge cases! For simple maps, use the map function of this library.
extension on Translations {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'loading': return 'loading...';
			case 'search_here': return 'Search Here...';
			case 'add_user': return 'Add User';
			case 'phone_number': return 'Phone Number';
			case 'email': return 'Email';
			case 'email_placeholder': return 'abc@gmail.com';
			case 'first_name': return 'First Name';
			case 'first_name_error': return 'Enter first name';
			case 'last_name': return 'Last Name';
			case 'last_name_error': return 'Enter last name';
			case 'select_user_role': return 'Select User Role';
			case 'select_your_role': return 'Select Your Role';
			case 'valid_email_error': return 'Enter valid email address';
			case 'select_role_error': return 'Select your role';
			case 'thank_you': return 'Thank You !';
			case 'sign_up_success': return 'You Sign Up successfully';
			case 'get_premium_at': return 'Get Premium At';
			case 'year_base_price': return '/Year Base price';
			case 'user_year': return 'user /year';
			case 'essential_features': return 'Get started with all the essential features';
			case 'user': return '1 User';
			case 'unlimited_entities': return 'Unlimited Entities';
			case 'unlimited_clients': return 'Unlimited Clients';
			case 'unlimited_assets': return 'Unlimited Assets';
			case 'unlimited_materials': return 'Unlimited Materials';
			case 'additional_users': return 'Additional Users';
			case 'add_to_plan': return 'Add them to your plan!';
			case 'proceed_to_pay': return 'Proceed To Pay';
			case 'welcome_message': return 'Hi, Welcome To AgTech! 👋';
			case 'first_name_label': return 'First Name';
			case 'first_name_hint': return 'First Name';
			case 'last_name_label': return 'Last Name';
			case 'last_name_hint': return 'Last Name';
			case 'phone_number_label': return 'Phone Number';
			case 'email_hint': return 'example@gmail.com';
			case 'otp_label': return 'OTP';
			case 'otp_hint': return 'Enter Your OTP';
			case 'password_hint': return 'Enter Your Password';
			case 'reenter_password_label': return 'Re-Enter Your Password';
			case 'sign_up_button': return 'Sign Up';
			case 'already_joined': return 'Already Joined us?';
			case 'login': return 'Login';
			case 'validation_error': return 'Validation Error';
			case 'otp_validation': return 'Enter a valid OTP';
			case 'send_otp': return 'Send OTP';
			case 'password_validation': return 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
			case 'welcome_back_message': return 'Hi, Welcome Back! 👋';
			case 'email_label': return 'Email';
			case 'password_label': return 'Password';
			case 'remember_me': return 'Remember Me';
			case 'forgot_password': return 'Forgot password';
			case 'login_button': return 'Login';
			case 'new_to_cold_storage': return 'New to cold storage?  ';
			case 'new_to_ag_tech': return 'New to AgTech?  ';
			case 'sign_up': return 'Sign up';
			case 'email_validation_error': return 'Enter valid email address';
			case 'password_error': return 'Enter password';
			case 'phone_number_hint': return 'Phone Number';
			case 'phone_number_error': return 'Enter phone number';
			case 'valid_phone_number_error': return 'Enter valid phone number';
			case 'home': return 'Home';
			case 'entity': return 'Entity';
			case 'entity_description': return 'Manage and track all your cold storage facilities, warehouses, farms, and growers';
			case 'vendors_and_customers': return 'Vendors and Customers';
			case 'vendors_and_customers_description': return 'Add, view, and manage your vendors and customers';
			case 'material': return 'Material';
			case 'material_description': return 'Create and organize your materials, categories, and units of measurement';
			case 'asset': return 'Asset';
			case 'asset_description': return 'Track your equipment, machinery, and other valuable assets';
			case 'create_password': return 'Create Password';
			case 'enter_new_password': return 'Enter New Password';
			case 're_enter_your_password': return 'Re-Enter Your Password';
			case 'please_enter_new_password': return 'Please enter your new password.';
			case 'password_requirements': return 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
			case 'passwords_do_not_match': return 'Passwords do not match';
			case 'logout': return 'Logout';
			case 'create_password_button': return 'Create Password';
			case 'account_name': return 'Account Name';
			case 'email_address': return 'Email Address';
			case 'street1': return 'Street 1';
			case 'street2': return 'Street 2';
			case 'country': return 'Country';
			case 'create_account': return 'Create Account!';
			case 'continue_text': return 'Continue';
			case 'address': return 'Address';
			case 'separator': return '.......................';
			case 'state': return 'State';
			case 'city': return 'City';
			case 'postal_code': return 'Postal Code';
			case 'different_billing_address': return 'Different Billing Address ?';
			case 'logo': return 'Logo';
			case 'default_language': return 'Default Language';
			case 'time_zone': return 'Time Zone';
			case 'description': return 'Description';
			case 'selectDefault_language': return 'Select default language';
			case 'select_timezone': return 'Select Timezone';
			case 'upload': return 'Upload';
			case 'empty_account_name': return 'Enter account name';
			case 'invalid_email': return 'Enter valid email address';
			case 'empty_street1': return 'Enter street 1';
			case 'empty_country': return 'Enter country';
			case 'empty_state': return 'Enter state';
			case 'empty_city': return 'Enter city';
			case 'empty_postal_code': return 'Enter postal code';
			case 'error_select_default_language': return '   Select default language';
			case 'error_select_timezone': return '   Select timezone';
			case 'languages_en': return 'English';
			case 'languages_sp': return 'Spanish';
			case 'user_list': return 'User List';
			case 'noUser_left': return 'No user left';
			case 'seats_available': return 'seats available';
			case 'update_user': return 'Update User';
			case 'inactive': return 'Inactive';
			case 'active': return 'Active';
			case 'update_user_button': return 'Update User';
			case 'enter_first_name': return 'Enter first name';
			case 'enter_last_name': return 'Enter last name';
			case 'select_your_role_error': return '   Select your role';
			case 'transaction': return 'Transaction';
			case 'date': return 'Date';
			case 'type': return 'Type';
			case 'noTransaction_found': return 'No Transaction Found';
			case 'sort_by': return 'Sort By';
			case 'dispatcher': return 'Dispatcher';
			case 'receiver': return 'Receiver';
			case 'customer': return 'Customer';
			case 'vendor': return 'Vendor';
			case 'transfer_in': return 'T-IN';
			case 'transfer_out': return 'T-OUT';
			case 'out': return 'OUT';
			case 'in_text': return 'IN';
			case 'search_placeholder': return 'Search...';
			case 'transaction_id': return 'Transaction ID';
			case 'transaction_date': return 'Transaction Date';
			case 'received': return 'Received';
			case 'damage': return 'Damage';
			case 'remaining': return 'Remaining';
			case 'adjust': return 'Adjust';
			case 'return_text': return 'Return';
			case 'transfer': return 'Transfer';
			case 'in_transit': return 'IN Transit';
			case 'status': return 'Status';
			case 'transaction_type': return 'Transaction Type';
			case 'available_quantity': return 'Available quantity';
			case 'return_quantity': return 'Return Quantity';
			case 'date_of_return': return 'Date of Return';
			case 'reason_of_return': return 'Reason Of Return';
			case 'comments_notes': return 'Comments/Notes';
			case 'confirm': return 'Confirm';
			case 'cancel': return 'Cancel';
			case 'add_new_user': return 'Add new user';
			case 'error_no_user_left': return 'Error';
			case 'no_user_left_message': return 'No user left';
			case 'valid_email': return 'Enter valid email address';
			case 'user_role': return 'User Role';
			case 'select_role': return '   Select your role';
			case 'select_role_text': return 'Select role';
			case 'count': return 'Count';
			case 'get_started_features': return 'Get started with all the essential features';
			case 'add_them_to_your_plan': return 'Add them to your plan!';
			case 'this_reflected_next_billing': return 'This will be reflected in your next billing cycle';
			case 'proceed': return 'Proceed';
			case 'setting': return 'Setting';
			case 'user_management': return 'User Management';
			case 'entity_settings': return 'Entity Settings';
			case 'account_setting': return 'Account Setting';
			case 'subscription': return 'Subscription';
			case 'reports': return 'Reports';
			case 'update_profile': return 'Update Profile';
			case 'enter_your_email': return 'Enter Your Email';
			case 'example_email': return 'example@gmail.com';
			case 'enter_valid_email': return 'Enter valid email address';
			case 'update': return 'Update';
			case 'update_password': return 'Update Password';
			case 're_enter_password': return 'Re-Enter Your Password';
			case 'profile': return 'Profile';
			case 'create_entity': return 'Create Entity';
			case 'reports_occurrences': return 'Reports Occurrences';
			case 'no_report_found': return 'No Report Found';
			case 'daily': return 'Daily';
			case 'weekly': return 'Weekly';
			case 'monthly': return 'Monthly';
			case 'entity_listing': return 'Entity Listing';
			case 'update_account': return 'Update Account';
			case 'back': return 'Back';
			case 'phone': return 'Phone Number';
			case 'street_1': return 'Street 1';
			case 'street_2': return 'Street 2';
			case 'billing_address': return 'Different Billing Address ?';
			case 'account_name_required': return 'Enter account name';
			case 'email_invalid': return 'Enter valid email address';
			case 'street_1_required': return 'Enter street 1';
			case 'country_required': return 'Enter country';
			case 'state_required': return 'Enter state';
			case 'city_required': return 'Enter city';
			case 'postal_code_required': return 'Enter postal code';
			case 'no_entity_found': return 'No Entity Found';
			case 'assigned': return 'Assigned';
			case 'remove': return 'Remove';
			case 'add': return 'Add';
			case 'cold_storage': return 'Cold Storage';
			case 'farmhouse': return 'Farmhouse';
			case 'save': return 'Save';
			case 'notifications': return 'Notifications';
			case 'no_notification_found': return 'No Notification Found';
			case 'has_transferred_new_material': return 'Has transferred a new material';
			case 'please_enter_phone_number': return 'Please enter phone number';
			case 'create_unit': return 'Create Unit';
			case 'material_name': return 'Material Name';
			case 'category': return 'Category';
			case 'measurement_of_unit': return 'Measurement of Unit';
			case 'unit_name': return 'Unit Name';
			case 'uom': return 'UOM';
			case 'action': return 'Action';
			case 'unit_of_measurements': return 'Unit Of Measurements';
			case 'select_unit_of_measurements': return '   Select unit of measurements';
			case 'add_new_material': return 'Add New Material';
			case 'no_material_found': return 'No Material Found';
			case 'add_material': return 'Add Material';
			case 'name': return 'Name';
			case 'edit': return 'Edit';
			case 'delete': return 'Delete';
			case 'create_material': return 'Create Material';
			case 'material_name_hint': return 'ex. Apple';
			case 'description_hint': return 'Description';
			case 'select_category': return 'Select Category';
			case 'select_uom': return 'Select UOM';
			case 'create_new_material': return 'Create New Material';
			case 'enter_material_name': return 'Enter material name';
			case 'enter_description': return 'Enter description';
			case 'enter_unit_name': return 'Enter unit name';
			case 'select_material_category': return 'Select material category';
			case 'select_material_uom': return 'Select material UOM';
			case 'add_material_quantity': return 'Add Material Quantity';
			case 'enter_name_of_unit': return 'Enter Name Of Unit';
			case 'unit_quantity': return 'Unit quantity';
			case 'enter_quantity': return 'Enter quantity';
			case 'quality_type': return 'Quality type';
			case 'quality_type_hint': return 'Quality Type';
			case 'storage_conditions': return 'Storage Conditions';
			case 'add_storage_conditions': return 'Add Storage Conditions';
			case 'safety_data': return 'Safety Data';
			case 'brief_safety_data': return 'Brief Safety Data Or Handling Instructions.';
			case 'compliance_certificates': return 'Compliance Certificates';
			case 'add_certificate': return 'Add Certificate';
			case 'regulatory_information': return 'Regulatory Information';
			case 'regulatory_information_hint': return 'Regulatory Information Or Restrictions.';
			case 'additional_information': return 'Additional Information';
			case 'create': return 'Create';
			case 'specification': return 'Specification';
			case 'add_imperial_unit': return 'Add Imperial Unit';
			case 'length': return 'Length';
			case 'length_hint': return 'Length';
			case 'width': return 'Width';
			case 'width_hint': return 'Width';
			case 'height': return 'Height';
			case 'height_hint': return 'Height';
			case 'diameter': return 'Diameter';
			case 'diameter_hint': return 'Diameter';
			case 'weight': return 'Weight';
			case 'weight_hint': return 'Weight';
			case 'color': return 'Color';
			case 'color_hint': return 'Color';
			case 'signature': return 'Signature';
			case 'no_content': return 'No content';
			case 'submit': return 'Submit';
			case 'image_path': return 'assets/images/ic_close_dialog.png';
			case 'background_color': return 'Colors.grey';
			case 'signature_background_color': return 'Colors.white';
			case 'dialog_warning_title': return 'Warning';
			case 'dialog_warning_message': return 'This is an irreversible action. Do you want to proceed?';
			case 'dialog_delete_title': return 'Alert';
			case 'dialog_delete_message': return 'Are you sure you want to delete this?';
			case 'dialog_ok_btn_text': return 'Proceed';
			case 'dialog_cancel_btn_text': return 'Cancel';
			case 'dialog_delete_ok_btn_text': return 'Yes';
			case 'dialog_delete_cancel_btn_text': return 'No';
			case 'dialog_ok_button_color': return '#005AFF';
			case 'dialog_cancel_button_color': return '#D9D9D9';
			case 'dialog_ok_button_text_color': return '#FFFFFF';
			case 'dialog_cancel_button_text_color': return '#000000';
			case 'dialog_title_color': return '#FF0000';
			case 'dialog_title_font_weight': return '500';
			case 'dialog_title_font_size': return '20';
			case 'dialog_content_color': return '#000000';
			case 'dialog_content_font_weight': return '500';
			case 'dialog_content_font_size': return '20';
			case 'dialog_img_limit_validation': return 'Upload Limit Reached';
			case 'dialog_upload_limit_warning': return 'You have reached the maximum upload limit.';
			case 'dialog_img_count_validation': return 'You can upload a maximum of 5 images.';
			case 'dialog_img_size_validation': return 'Total upload size cannot exceed 10 MB.';
			case 'dialog_ok_text': return 'Ok';
			case 'pageHeading': return 'Specification';
			case 'addImperialUnit': return 'Add Imperial Unit';
			case 'update_material_quantity': return 'Update Material Quantity';
			case 'select_a_quality_type': return 'Select a quality type';
			case 'brief_safety_data_or_handling_instructions': return 'Brief Safety data or handling instructions.';
			case 'regulatory_information_or_restrictions': return 'Regulatory information or restrictions.';
			case 'enter_tag': return 'Enter tag...';
			case 'add_category': return 'Add Category';
			case 'update_material': return 'Update Material';
			case 'select_bin': return 'Select Bin';
			case 'need_custom_mapping': return 'Need Custom Mapping';
			case 'select_material': return 'Select Material';
			case 'your_account': return 'Your Account';
			case 'details': return 'Details';
			case 'incoming_material': return 'Incoming Material';
			case 'reject': return 'Reject';
			case 'accept': return 'Accept';
			case 'quantity': return 'Quantity';
			case 'receipt_date': return 'Receipt Date';
			case 'driver_name': return 'Driver Name';
			case 'material_in_successfully': return 'Material IN Successfully';
			case 'dashboard': return 'V&C Dashboard';
			case 'material_transfer': return 'Material Transfer';
			case 'date_of_transfer': return 'Date of Transfer';
			case 'expiration_date': return 'Expiration Date';
			case 'quantity_transfer': return 'Quantity Transfer';
			case 'reason_for_transfer': return 'Reason for Transfer';
			case 'generate': return 'Generate';
			case 'add_transfer_date': return 'Add transfer date';
			case 'enter_quantity_more_than_0': return 'Enter quantity more than 0';
			case 'no_quantity_available': return 'No quantity available for out';
			case 'not_enough_quantity': return 'Not enough quantity available to dispatch';
			case 'material_transfer_success': return 'Material Transfer Successfully';
			case 'transfer_request': return 'Transfer Request';
			case 'entity_from': return 'Entity From';
			case 'entity_to': return 'Entity To';
			case 'material_in_transit': return 'Material is in Transit';
			case 'add_quantity': return 'Add Quantity';
			case 'quantity_dispatched': return 'Quantity Dispatched';
			case 'notes': return 'Notes';
			case 'upload_images': return 'Upload Images';
			case 'view_all': return 'View All';
			case 'add_images': return 'Add Images';
			case 'supports': return 'Supports: PNG, JPG, JPEG, WEBP';
			case 'select_category_error': return '   Select a category';
			case 'select_material_error': return '   Select a material';
			case 'enter_quantity_more_than_zero': return 'Enter quantity more than 0';
			case 'add_more_quantity': return 'Add More Quantity';
			case 'transportation_details': return 'Transportation Details';
			case 'add_signature': return 'Add Signature';
			case 'click_here_to_draw_signature': return 'Click here to draw signature';
			case 'bin': return 'Bin';
			case 'material_out': return 'Material OUT';
			case 'date_of_dispatch': return 'Date of Dispatch';
			case 'select': return 'Select';
			case 'please_add_quantity': return 'Please add quantity';
			case 'please_add_signature': return 'Please add signature';
			case 'error': return 'Error';
			case 'select_customer_name': return 'Select a customer name';
			case 'select_entity': return 'Select an entity';
			case 'enter_entity_name': return 'Enter entity name';
			case 'select_date_of_dispatch': return 'Select date of dispatch';
			case 'date_of_dispatch_hint': return 'Date of Dispatch';
			case 'warning': return 'Warning';
			case 'irreversible_action': return 'This is an irreversible action. Do you want to proceed?';
			case 'alert': return 'Alert';
			case 'yes': return 'Yes';
			case 'no': return 'No';
			case 'delete_confirmation': return 'Are you sure you want to delete this item?';
			case 'add_photo': return 'Add Photo';
			case 'camera': return 'Camera';
			case 'library': return 'Library';
			case 'take_photo_from': return 'From where do you want to take the photo?';
			case 'update_quantity': return 'Update Quantity';
			case 'select_unit': return 'Select Unit';
			case 'select_a_category': return 'Select a category';
			case 'select_a_material': return 'Select a material';
			case 'select_a_unit': return 'Select a unit';
			case 'enter_more_than_zero': return 'Enter quantity more than 0';
			case 'select_bin_prompt': return 'Select Bin';
			case 'notes_hint': return 'Notes';
			case 'quantity_hint': return 'Quantity';
			case 'text_material_in_update': return 'Material IN Update';
			case 'text_entity': return 'Entity';
			case 'text_vendor': return 'Vendor';
			case 'text_date_of_receipt': return 'Date of Receipt';
			case 'text_add_quantity': return 'Add Quantity';
			case 'text_add_more_quantity': return 'Add more Quantity';
			case 'text_select': return 'Select';
			case 'text_select_a_vendor': return 'Select a vendor';
			case 'text_select_date_of_receipt': return 'Select date of receipt';
			case 'text_update_material': return 'Update Material';
			case 'text_back': return 'Back';
			case 'text_generate': return 'Generate';
			case 'text_error': return 'Error';
			case 'text_please_add_signature': return 'Please add signature';
			case 'text_driver_name': return 'Driver Name';
			case 'text_signature': return 'Signature';
			case 'text_add_signature': return 'Add Signature';
			case 'text_click_here_draw_signature': return 'Click here to draw signature';
			case 'text_bin': return 'Bin';
			case 'text_quantity': return 'Quantity';
			case 'text_uom': return 'UOM';
			case 'text_transportation_details': return 'Transportation Details';
			case 'text_thank_you': return 'Thank You !';
			case 'text_material_updated': return 'Material Updated Successfully';
			case 'text_material_in_success': return 'Material IN Successfully';
			case 'text_dashboard': return 'Dashboard';
			case 'text_category': return 'Category';
			case 'text_select_category': return 'Select Category';
			case 'text_material': return 'Material';
			case 'text_select_material': return 'Select Material';
			case 'text_unit': return 'Unit';
			case 'text_select_unit': return 'Select Unit';
			case 'text_expiration_date': return 'Expiration Date';
			case 'text_quantity_received': return 'Quantity Received';
			case 'text_damage_quantity_received': return 'Damage Quantity Received';
			case 'text_any_damage': return 'Any Damage';
			case 'text_upload_images': return 'Upload Images';
			case 'text_view_all': return 'View All';
			case 'text_add_images': return 'Add Images';
			case 'text_supports_formats': return 'Supports: PNG, JPG, JPEG, WEBP';
			case 'text_material_in': return 'Material IN';
			case 'text_error_enter_entity_name': return 'Enter entity name';
			case 'text_error_select_vendor': return '   Select a vendor';
			case 'text_error_select_date': return 'Select date of receipt';
			case 'text_error_add_quantity': return 'Please add quantity';
			case 'text_error_add_signature': return 'Please add signature';
			case 'text_error_enter_driver_name': return 'Enter driver name';
			case 'text_click_to_draw_signature': return 'Click here to draw signature';
			case 'text_na': return 'NA';
			case 'text_select_bin': return 'Select Bin';
			case 'text_error_select_category': return '   Select a category';
			case 'text_error_select_material': return '   Select a material';
			case 'text_error_select_unit': return '   Select a unit';
			case 'text_error_enter_quantity': return 'Enter quantity';
			case 'text_error_enter_damage_quantity': return 'Enter damage quantity';
			case 'text_error_damage_quantity_must_be_less': return 'Damage quantity must be less than received quantity';
			case 'hint_select_category': return 'Select Category';
			case 'hint_select_material': return 'Select Material';
			case 'hint_select_unit': return 'Select Unit';
			case 'hint_expiration_date': return 'Expiration Date';
			case 'hint_quantity': return 'Quantity';
			case 'hint_damage_quantity': return 'Quantity';
			case 'text_any_breakage': return 'Any Breakage';
			case 'text_supported_formats': return 'Supports: PNG, JPG, JPEG, WEBP';
			case 'error_empty_quantity': return 'Please add quantity first';
			case 'text_inventory': return 'Inventory';
			case 'text_unit_name': return 'Unit Name';
			case 'text_type': return 'Type';
			case 'error_message': return 'Please add quantity first';
			case 'text_transaction': return 'Transaction';
			case 'text_no_transaction_found': return 'No Transaction Found';
			case 'icon_back_button': return 'assets/images/ic_back_btn.png';
			case 'icon_home': return 'assets/images/default/ic_home.svg';
			case 'icon_notification': return 'assets/images/ic_notification_bell.png';
			case 'image_empty_list': return 'assets/images/ic_blank_list.png';
			case 'header_transaction_date': return 'Transaction Date';
			case 'header_received': return 'Received';
			case 'header_remaining': return 'Remaining';
			case 'return_quantity_hint': return 'Return Quantity';
			case 'date_of_return_hint': return 'Date of Return';
			case 'information_hint': return 'Information';
			case 'comments_notes_hint': return 'Information';
			case 'enter_quantity_error': return 'Enter quantity';
			case 'not_enough_quantity_error': return 'Not have enough quantity available';
			case 'select_date_error': return 'Select date of return';
			case 'enter_reason_error': return 'Enter reason for return';
			case 'text_field_placeholder': return '.................................................................................................................................................................................................................................................';
			case 'return_button_text': return 'Return';
			case 'adjust_button_text': return 'Adjust';
			case 'type_of_adjustment_text': return 'Type Of Adjustment';
			case 'remove_text': return 'Remove';
			case 'add_text': return 'Add';
			case 'available_quantity_text': return 'Available Quantity';
			case 'quantity_adjusted_text': return 'Quantity Adjusted';
			case 'date_of_adjustment_text': return 'Date of Adjustment';
			case 'select_date_of_adjustment_text': return 'Select date of adjustment';
			case 'reason_for_adjustment_text': return 'Reason for Adjustment';
			case 'enter_reason_of_adjustment_text': return 'Enter reason for adjustment';
			case 'comments_notes_text': return 'Comments/Notes';
			case 'transaction_id_text': return 'Transaction ID';
			case 'transaction_date_text': return 'Transaction Date';
			case 'type_text': return 'Type';
			case 'vendor_text': return 'Vendor';
			case 'received_text': return 'Received';
			case 'remaining_text': return 'Remaining';
			case 'bin_text': return 'Bin';
			case 'expiry_date_text': return 'Expiry Date';
			case 'transaction_detail_text': return 'Transaction Detail';
			case 'perform_action_text': return 'Do you want to perform action?';
			case 'inventory_text': return 'Inventory';
			case 'material_text': return 'Material';
			case 'category_text': return 'Category';
			case 'quantity_text': return 'Quantity';
			case 'no_inventory_found_text': return 'No Inventory Found';
			case 'sort_by_hint_text': return 'Sort By';
			case 'client_text': return 'Client';
			case 'materials_text': return 'Materials';
			case 'total_quantity_text': return 'Total Quantity';
			case 'gallery_text': return 'Gallery';
			case 'no_image_found_text': return 'No Image Found';
			case 'reset_password_text': return 'Reset Password';
			case 'change_password_text': return 'Change Password';
			case 'verification_code_prompt': return 'Please enter your verification code.';
			case 'verification_code_info': return 'We have sent a verification code to your registered email ID.';
			case 'enter_otp_label': return 'Enter Your OTP';
			case 'enter_otp_hint': return 'Enter Your OTP';
			case 'enter_new_password_label': return 'Enter New Password';
			case 'enter_new_password_hint': return 'Enter New Password';
			case 'reenter_password_hint': return 'Enter Your Password';
			case 'password_validation_error': return 'Password must contain 8+ characters with combination of uppercase, lowercase, numbers & symbols';
			case 'otp_validation_error': return 'Enter valid otp';
			case 'forgot_password_title': return 'Forgot Password';
			case 'submit_button_text': return 'Submit';
			case 'registered_email_prompt': return 'Please enter your registered email ID.';
			case 'registered_email_prompt_desc_text': return 'We will send a verification code to your registered email ID.';
			case 'update_farm_grower_title': return 'Update Farm/Grower';
			case 'farm_name_label': return 'Farm Name';
			case 'farm_name_validation_error': return 'Enter farm name';
			case 'address_label': return 'Address';
			case 'address_hint': return 'Address';
			case 'address_validation_error': return 'Enter address';
			case 'phone_label': return 'Phone';
			case 'profile_picture_label': return 'Profile Picture';
			case 'upload_button_text': return 'Upload';
			case 'farm_size_label': return 'Farm Size (Acres)';
			case 'farm_size_validation_error': return 'Enter farm size';
			case 'type_of_farming_label': return 'Type Of Farming';
			case 'additional_details_label': return 'Additional Details';
			case 'owner_name': return 'Owner Name';
			case 'created_by': return 'Created By';
			case 'manager_name': return 'Manager Name';
			case 'farming_method': return 'Farming Method';
			case 'irrigation_system': return 'Irrigation System';
			case 'type_of_soil': return 'Type Of Soil';
			case 'storage_facilities': return 'Storage Facilities';
			case 'add_button': return 'Update Entity';
			case 'farming_method_hint': return 'Farming Method';
			case 'irrigation_system_hint': return 'Details of Irrigation System Used';
			case 'type_of_soil_hint': return 'Add Soil Type';
			case 'compliance_certificates_hint1': return 'Add Certificate';
			case 'compliance_certificates_hint2': return 'Enter tag...';
			case 'storage_facilities_hint1': return 'Add Storage Facility';
			case 'storage_facilities_hint2': return 'Enter tag...';
			case 'add_farm_grower': return 'Add Farm/Grower';
			case 'add_entity': return 'Add Entity';
			case 'entity_list': return 'Entity List';
			case 'location': return 'Location';
			case 'request': return 'Request';
			case 'setup_finish': return 'Setup Finish';
			case 'cold_storage_warehouse': return 'Cold Storage | Warehouse';
			case 'farm_grower': return 'Farm | Grower';
			case 'create_cold_storage_subheading': return 'Create and manage your cold storage and/or warehouses for efficient storage and distribution.';
			case 'create_farmhouse_subheading': return 'Add and oversee your farms and/or growers to track production and inventory.';
			case 'entity_details': return 'Entity Details';
			case 'material_in': return 'Material In';
			case 'view_inventory': return 'View Inventory';
			case 'view_transactions': return 'Transaction Log';
			case 'update_cold_storage': return 'Update Cold Storage/Warehouse';
			case 'additional_details': return 'Additional Details';
			case 'storage_name': return 'Storage Name';
			case 'profile_picture': return 'Profile Picture';
			case 'add_bin': return 'Add Bin';
			case 'add_more_bin': return 'Add more Bin';
			case 'storage_capacity': return 'Storage Capacity';
			case 'temperature_range': return 'Temperature Range (°F)';
			case 'regulation_information': return 'Regulation Information';
			case 'safety_measures': return 'Safety Measures';
			case 'add_safety_measures': return 'Add Safety Measures';
			case 'operational_hours': return 'Operational Hours';
			case 'update_entity': return 'Update Entity';
			case 'add_cold_storage': return 'Add Cold Storage/Warehouse';
			case 'storage_condition': return 'Storage Condition';
			case 'select_storage': return 'Select a storage';
			case 'select_manager_hint': return 'Select Manager';
			case 'select_manager_error_text': return '   Select a manager';
			case 'enter_storage_condition': return 'Enter storage condition';
			case 'max_limit_250_words': return 'Max limit 250 words';
			case 'enter_storage_capacity': return 'Enter storage capacity';
			case 'bin_creation': return 'Bin Creation';
			case 'bin_name': return 'Bin Name';
			case 'enter_bin_name': return 'Enter bin name';
			case 'type_of_storage': return 'Type Of Storage';
			case 'select_type_of_storage': return 'Select Type Of Storage';
			case 'select_a_storage': return '   Select a storage';
			case 'max_temp': return 'Max Temp';
			case 'max_button_text': return 'Max';
			case 'enter_max_temp': return 'Enter max temp';
			case 'must_be_a_number': return 'Must be a number';
			case 'must_be_greater_than_max': return 'Must be greater than Max';
			case 'min_temp': return 'Min Temp';
			case 'min_button_text': return 'Min';
			case 'enter_min_temp': return 'Enter min temp';
			case 'must_be_less_than_max': return 'Must be less than Max';
			case 'humidity_range': return 'Humidity Range (%)';
			case 'max_humidity': return 'Max Humidity';
			case 'enter_max_humidity': return 'Enter max humidity';
			case 'min_humidity': return 'Min Humidity';
			case 'enter_min_humidity': return 'Enter min humidity';
			case 'update_bin': return 'Update Bin';
			case 'greater_than_max': return 'Must be greater than Max';
			case 'less_than_max': return 'Must be less than Max';
			case 'bin_name_hint': return 'Bin name';
			case 'storage_condition_hint': return 'Information';
			case 'storage_capacity_hint': return 'Storage Capacity';
			case 'enter_storage_name': return 'Enter storage name';
			case 'asset_creation': return 'Asset Creation';
			case 'basic_asset_information': return 'Basic Asset Information';
			case 'purchase_and_financial_details': return 'Purchase and Financial Details';
			case 'operational_details': return 'Operational Details';
			case 'insurance_and_compliance': return 'Insurance and Compliance';
			case 'purchase_date': return 'Purchase Date';
			case 'insurance_expiry_date': return 'Insurance Expiry Date';
			case 'insurance_provider': return 'Insurance Provider';
			case 'insurance_policy_number': return 'Insurance Policy Number';
			case 'purchase_price': return 'Purchase Price';
			case 'vendor_name': return 'Vendor Name';
			case 'vendor_contact_number': return 'Vendor Contact Number';
			case 'vendor_email': return 'Vendor Email';
			case 'invoice_number': return 'Invoice Number';
			case 'warranty_details': return 'Warranty Details';
			case 'asset_name': return 'Asset Name';
			case 'manufacturer': return 'Manufacturer';
			case 'model': return 'Model';
			case 'serial_number': return 'Serial Number';
			case 'operational_status': return 'Operational Status';
			case 'condition': return 'Condition';
			case 'last_updated': return 'Last Updated';
			case 'create_new_asset': return 'Create New Asset';
			case 'no_asset_found': return 'No Asset Found';
			case 'create_asset': return 'Create Asset';
			case 'current_location': return 'Current Location';
			case 'assigned_to': return 'Assigned To';
			case 'available': return 'Available';
			case 'occupied': return 'Occupied';
			case 'assign': return 'Assign';
			case 'assign_new': return 'Assign New';
			case 'release': return 'Release';
			case 'history': return 'History';
			case 'no_history_found': return 'No History Found';
			case 'date_from': return 'Date from';
			case 'date_to': return 'Date To';
			case 'yyyy_mm_dd': return 'YYYY-MM-DD';
			case 'blank_list_image': return 'assets/images/ic_blank_list.png';
			case 'calendar_image': return 'assets/images/ic_calender.png';
			case 'create_asset_category': return 'Create Asset Category';
			case 'category_name': return 'Category Name';
			case 'enter_category_name': return 'Enter category name';
			case 'brief_description': return 'Brief Description';
			case 'create_category': return 'Create Category';
			case 'close_dialog_image': return 'assets/images/ic_close_dialog.png';
			case 'new_assign': return 'New Assign';
			case 'select_location': return 'Select location';
			case 'asset_cant_be_assigned': return 'Asset can\'t be assigned to it\'s current location';
			case 'select_user': return 'Select user';
			case 'end_date': return 'End Date';
			case 'enter_end_date': return 'Enter end date';
			case 'usage': return 'Usage';
			case 'enter_usage': return 'Enter usage';
			case 'note': return 'Note';
			case 'brief_usage': return 'Brief Usage';
			case 'note_hint': return 'Note';
			case 'end_date_hint': return 'End Date';
			case 'model_number_hint': return 'Model number';
			case 'asset_updation': return 'Asset Updation';
			case 'divider_color': return '#E7E7E7';
			case 'arrow_up_icon': return 'assets/images/ic_arrow_up.png';
			case 'arrow_down_icon': return 'assets/images/ic_arrow_down.png';
			case 'calendar_icon': return 'assets/images/ic_calender.png';
			case 'back_button_icon': return 'assets/images/ic_back_btn.png';
			case 'update_asset': return 'Update Asset';
			case 'select_asset_category_error_text': return '   Select asset category';
			case 'enter_asset_name__error_text': return 'Enter asset name';
			case 'enter_manufacturer_error_text': return 'Enter manufacturer';
			case 'enter_model_number_error_text': return 'Enter model number';
			case 'enter_serial_number_error_text': return 'Enter serial number';
			case 'inventory': return 'Inventory';
			case 'no_transaction_found': return 'No Transaction Found';
			case 'transaction_detail': return 'Transaction Detail';
			case 'do_you_want_to_perform_action': return 'Do you want to perform action?';
			case 'unit': return 'Unit';
			case 'quantity_type_name': return 'NA';
			case 'type_of_adjustment': return 'Type Of Adjustment';
			case 'quantity_adjusted': return 'Quantity Adjusted';
			case 'date_of_adjustment': return 'Date of Adjustment';
			case 'reason_for_adjustment': return 'Reason for Adjustment';
			case 'hint_date_of_return': return 'Date of Return';
			case 'hint_information': return 'Information';
			case 'hint_comments_notes': return 'Information';
			case 'select_date_of_return': return 'Select date of return';
			case 'enter_reason_for_return': return 'Enter reason for return';
			case 'no_inventory_found': return 'No Inventory Found';
			case 'total_quantity': return 'Total Quantity';
			case 'enter_name': return 'Enter name';
			case 'enter_street_1': return 'Enter street 1';
			case 'enter_country': return 'Enter country';
			case 'enter_state': return 'Enter state';
			case 'enter_city': return 'Enter city';
			case 'enter_postal_code': return 'Enter postal code';
			case 'add_primary_contact': return 'Add Primary Contact';
			case 'point_of_contact': return 'Point Of Contact';
			case 'contact_name': return 'Contact Name';
			case 'enter_contact_name': return 'Enter contact name';
			case 'contact_number': return 'Contact Number';
			case 'add_vendor_customer': return 'Add Vendor & Customer';
			case 'search_by_account_name': return 'Search by Account Name';
			case 'no_account_found': return 'No Account found with this name';
			case 'send_request': return 'Send Request';
			case 'you_want_to_add_them_as': return 'You want to add them as';
			case 'connected': return 'Connected';
			case 'incoming_request': return 'Incoming Request';
			case 'request_sent': return 'Request Sent';
			case 'v_c_list': return 'V&C List';
			case 'no_record_found': return 'No Record Found';
			case 'create_new_vendor': return 'Create New Vendor';
			case 'request_rejected': return 'Request Rejected';
			case 'v_and_c_detail': return 'V&C Detail';
			case 'name_of_person': return 'Name Of Person';
			case 'account': return 'Account';
			case 'account_name_hint': return 'Account Name';
			case 'location_hint': return 'Location';
			case 'phone_hint': return 'Phone number';
			case 'manager': return 'Manager';
			case 'edit_client': return 'Edit Client';
			case 'decline': return 'Decline';
			case 'enter_street_2': return 'Enter street 2';
			case 'enter_valid_email_address': return 'Enter valid email address';
			case 'brief_description_of_material': return 'Brief description of the material';
			case 'create_category_button': return 'Create Category';
			case 'brief_description_of_the_material': return 'Brief Description Of The Material';
			case 'warning_title': return 'Warning';
			case 'proceed_button_text': return 'Proceed';
			case 'cancel_button_text': return 'Cancel';
			case 'admin_role': return 'Admin';
			case 'manager_role': return 'Manager';
			case 'employee_role': return 'Employee';
			case 'assign_text': return 'Assign';
			case 'status_text': return 'Status';
			case 'active_status': return 'Active';
			case 'inactive_status': return 'Inactive';
			case 'email_address_label': return 'Email Address';
			case 'status_label': return 'Status';
			case 'details_label': return 'Details';
			case 'assign_by_label': return 'Assign By';
			case 'usage_label': return 'Usage';
			case 'note_label': return 'Note';
			case 'from_label': return 'From';
			case 'to_label': return 'To';
			case 'close_button_label': return 'Close';
			case 'success_text': return 'Success';
			case 'error_text': return 'Error';
			case 'validation_error_text': return 'Validation Error';
			case 'account_created_success_text': return 'Account created successfully';
			case 'session_expired_text': return 'Session is expired or invalid need to login again';
			case 'subscribed_success_text': return 'Subscribed successfully';
			case 'category_added_success_text': return 'Category added successfully';
			case 'record_delete_success_text': return 'Record has been successfully deleted';
			case 'entity_created_success_text': return 'Entity created successfully';
			case 'material_created_success_text': return 'Material created successfully';
			case 'added_text': return 'Added';
			case 'material_unit_added_success_text': return 'Material unit added successfully';
			case 'signup_success_text': return 'Signed up successfully';
			case 'login_success_text': return 'Logged in successfully';
			case 'user_created_success_text': return 'User created successfully';
			case 'otp_sent_text': return 'OTP SENT';
			case 'otp_sent_message_text': return 'Sent an OTP at your email, please check. OTP will be valid till next 2 minutes';
			case 'first_name_last_name_email_required': return 'First name, Last name, Email is required';
			case 'transaction_adjusted_success_text': return 'Transaction adjusted successfully';
			case 'transaction_return_success_text': return 'Transaction return successfully';
			case 'account_updated_success_text': return 'Account updated successfully';
			case 'record_updated_success_text': return 'Record updated successfully';
			case 'request_accepted_success_text': return 'Request accept successfully';
			case 'request_declined_success_text': return 'Request declined successfully';
			case 'request_sent_success_text': return 'Request sent successfully';
			case 'record_created_success_text': return 'Record created successfully';
			case 'asset_updated_success_text': return 'Asset updated successfully';
			case 'asset_assigned_success_text': return 'Asset assigned successfully';
			case 'asset_success_release_text': return 'Asset successfully release';
			case 'asset_created_success_text': return 'Asset created successfully';
			case 'password_updated_success_text': return 'Password updated successfully';
			case 'entity_updated_success_text': return 'Entity updated successfully';
			case 'material_unit_updated_success_text': return 'Material unit updated successfully';
			case 'material_transfer_rejected_text': return 'Material transfer rejected';
			case 'quantity_added_success_text': return 'Quantity Added Successfully';
			case 'transaction_updated_success_text': return 'Transaction Updated Successfully';
			case 'quantity_updated_success_text': return 'Quantity updated successfully';
			case 'transfer_request_sent_success_text': return 'Transfer request sent Successfully';
			case 'material_request_accepted_success_text': return 'Material request accepted successfully';
			case 'material_request_rejected_success_text': return 'Material request rejected successfully';
			case 'selected_material_mapped_success_text': return 'Selected material mapped successfully';
			case 'user_updated_success_text': return 'User updated successfully';
			case 'user_removed_from_entity': return 'User removed from the entity';
			case 'user_assigned_to_entity': return 'User successfully assigned to the entity';
			case 'bin_name_already_exists_text': return 'The bin name is already exists';
			case 'bin_created_success_text': return 'Bin created successfully';
			case 'bin_updated_success_text': return 'Bin updated successfully';
			case 'email_sent_success_text': return 'Email sent successfully';
			case 'password_reset_success_text': return 'Password reset successfully';
			case 'report_request_save_success_text': return 'Report request save successfully';
			case 'profile_updated_success_text': return 'Profile updated successfully';
			case 'subscribe_updated_success_text': return 'Subscribe updated successfully';
			case 'account_delete_permission_text': return 'Do you want to delete this account ?';
			case 'account_delete_warning_text': return 'This will delete your account permanently.';
			case 'account_deleted_success_text': return 'Account deleted successfully.';
			default: return null;
		}
	}
}

